# Use official PostgreSQL image
FROM postgres:15

# Set environment variables for the database
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_DB=${POSTGRES_DB}

# Expose PostgreSQL port
EXPOSE 5432
