name: Deploy to Azure ACI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_ACR_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Set up Docker Compose
        run: |
          sudo apt-get install docker-compose

      - name: Build Docker images using Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

      - name: Tag Docker images for ACR
        run: |
          docker tag restaurant-booking-system_app:latest ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/restaurant-booking-system_app:latest

      - name: Push Docker images to Azure Container Registry
        run: |
          docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/app:latest
